### ISSUE TITLE
Missing material images

### ISSUE THREAD

**Issue by Ling53** [RetroJohn86/PoGo-Unpacked-APK#1]
Thanks for your work. I cannot find the material images of the origin pm0483, pm0484, and pm0487. Can you update them pls?

**Comment by RetroJohn86** [comment]
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm483.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm483.s.icon.png

https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm483.fORIGIN.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm483.fORIGIN.s.icon.png

https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm484.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm484.s.icon.png

https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm484.fORIGIN.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm484.fORIGIN.s.icon.png

https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm487.fALTERED.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm487.fALTERED.s.icon.png

https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm487.fORIGIN.icon.png
https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Sprite/pm487.fORIGIN.s.icon.png

change wording from Sprite Too Texture2D to get x256 version, also you can find them here https://github.com/RetroJohn86/Pokemon-Go-Assets-Sprites

**Comment by Ling53** [comment]
Thank you! But i want the Texture images of pm483.fORIGIN, pm484.fORIGIN and pm487.fORIGIN.
Like this https://github.com/RetroJohn86/PoGo-Unpacked-APK/blob/main/Unpacked%20Download/Animator/pm/pm0383_00_Rig/pm0383_00_BodyAll1.png.

**Comment by RetroJohn86** [comment]
Updated Files List too ( Start Dex Number too End Dex Number ) e.g. pm/0001-0151 etc. Folder under max Files Number now.

**Comment by Ling53** [comment]
nice!

**Comment by Ling53** [comment]
pm484.fORIGIN is still missing and can you export the animations of the pm？

**Comment by RetroJohn86** [comment]
added
